services:
  postgres:
    image: postgres:16-alpine
    container_name: coffee-postgres
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee
      POSTGRES_DB: coffee_loyalty
    ports:
      - "5433:5432"
    volumes:
      - coffee_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: coffee-redis
    ports:
      - "6380:6379"
    volumes:
      - coffee_redis:/data

volumes:
  coffee_pgdata:
  coffee_redis:
